name: CI
on:
  push:
    branches-ignore:
      - 'update-dependencies'
      - 'dependabot/*'
  pull_request:

jobs:
  linters:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Git Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Run linter
        run: "pylint nyanyabot/ --rcfile=.pylintrc"
