name: CI
on:
  push:
    branches-ignore:
      - 'update-dependencies'
      - 'dependabot/*'
  pull_request:
env:
  PY_COLORS: "1"
  MYPY_FORCE_TERMINAL_WIDTH: "180"

jobs:
  linters:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - testenv: pylint
            args: "nyanyabot/ --rcfile=.pylintrc"
          - testenv: bandit
            args: "-r nyanyabot/ -f custom --msg-template \"{relpath}:{line}: {test_id}: {severity}: {msg}\""
          - testenv: mypy
            args: "-p nyanyabot"

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            .mypy_cache
            ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.testenv }}-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
          restore-keys: ${{ runner.os }}-${{ matrix.testenv }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Set up problem matchers
        run: "python .github/problemmatchers.py ${{ matrix.testenv }} ${{ runner.temp }}"

      - name: Run linter
        run: "${{ matrix.testenv }} ${{ matrix.args }}"
